CREATE TABLE ticketbooking.events(

 EVENT_ID BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
 EVENT_NAME VARCHAR(50),
 EVENT_TYPE VARCHAR(50),
 LOCATION VARCHAR(50),
 CONDUCTED_BY VARCHAR(50),
 EVENT_DATE DATETIME,
 EVENT_STATUS VARCHAR(50),
 AVAILABLE_TICKETS INT,
 REASON VARCHAR(50),
 PRICE DOUBLE,
 CREATED_BY VARCHAR(50),
 CREATED_ON DATETIME,
 UPDATED_BY VARCHAR(50),
 UPDATED_ON DATETIME

);


CREATE TABLE ticketbooking.PAYMENT_DETAILS(

 PAYMENT_ID BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
 USER_ID VARCHAR(50),
 BOOKING_ID VARCHAR(50),
 PAYMENT_STATUS VARCHAR(50),
 PAYMENT_MODE VARCHAR(50),
 CANCELLATION_ID DATETIME,
 CANCELLATION_REASON VARCHAR(100),
 REFUND_STATUS VARCHAR(50),
 CREATED_BY VARCHAR(50),
 CREATED_ON DATETIME,
 UPDATED_BY VARCHAR(50),
 UPDATED_ON DATETIME

);


CREATE TABLE ticketbooking.TICKET(

 TCKT_NBR BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
 EVENT_ID INT,
 BOOKING_ID VARCHAR(50),
 USER_ID VARCHAR(50),
 BOOKING_STATUS VARCHAR(50),
 EVENT_DATE DATETIME,
 EVENT_NAME VARCHAR(50),
 EVENT_LOCATION VARCHAR(50),
 EVENT_TYPE VARCHAR(50),
 CONDUCTED_BY VARCHAR(50),
 NO_OF_TICKETS INT,
 PRICE DOUBLE,
 CREATED_BY VARCHAR(50),
 CREATED_ON DATETIME,
 UPDATED_BY VARCHAR(50),
 UPDATED_ON DATETIME

);


CREATE TABLE ticketbooking.USER_DETAILS(

 USER_NBR BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
 USER_ID VARCHAR(50),
 USER_NAME VARCHAR(50),
 MOBILE_NO VARCHAR(50),
 EMAIL_ID VARCHAR(50),
 PASSWORD VARCHAR(50),
 ROLE VARCHAR(50),
 CREATED_BY VARCHAR(50),
 CREATED_ON DATETIME,
 UPDATED_BY VARCHAR(50),
 UPDATED_ON DATETIME

);