spring.application.name=deltascribe-backend
server.port=8080
server.servlet.context-path=/deltascribe

# H2 Database Configuration
spring.datasource.url=jdbc:h2:mem:deltascribedb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# SQL Initialization Configuration (Optional, if we want to preload data)
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:scripts/data.sql
spring.jpa.defer-datasource-initialization=true
