# Server Config
server.port=8080
# server.servlet.context-path=/api

# Database Configuration (In-Memory H2 for high performance & no file locking)
spring.datasource.url=jdbc:h2:mem:tpf_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

# JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true
spring.h2.console.settings.trace=false

# File Upload Configuration
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Custom Security Keys and Storage Settings
tpf.jwt.secret=9a67678f26cf94c03b1239c0f9914cb7b4946399c5c160a373b9e4a8cb88f7b30c4516ecb1bf870fb33777a83d3e69f8c126d57b565a5198ec4cf1a1de06b2ef
tpf.jwt.expiration-ms=3600000
tpf.upload.dir=./uploads

# Logging Configuration
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - [X-Correlation-ID: %X{correlationId}] - %msg%n
logging.level.com.tataplay.fiber.onboarding=DEBUG
logging.level.org.springframework.security=INFO

# Caching
#spring.cache.type=concurrentmap
